<?php
/**
 * Created by PhpStorm.
 * User: hoangkhai
 * Date: 9/20/18
 * Time: 9:47 PM
 */
require '../../class/Abstract_class.php';

class Student extends Abstract_class
{
    /**
     * category constructor.
     */
    public function __construct()
    {
        parent::__construct('student');

    }

    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    public function addCategories($name)
    {
        return parent::addCategories($name); // TODO: Change the autogenerated stub
    }

    public function update($id, $name)
    {
        parent::update($id, $name); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function getIdByNme($id)
    {
        return parent::getIdByNme($id); // TODO: Change the autogenerated stub
    }
}